### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by mrelg** [falk-hueffner/metric-cooking#11]
Spices like cinnamon, paprika, and minced rosemary should be in [g] not [ml] 
https://foodwishes.blogspot.com/2012/03/st-patricks-day-special-irish-shepherds.html

Great extension !!!!!!!!!! Infinitely better than"Cooking Converter".
It just needs a little larger database of ingredients for cross-dimensional conversions.

Also control panel for preferred units and database access for customization wouldn't be amiss.

**Comment by falk-hueffner** [comment]
1/8 tsp cinnamon is about 0.3g, 1 tsp paprika is about 2.5g, and 2 tsp minced fresh rosemary is, not sure, maybe 3g. Currently I don't show anything less than 4 grams, because I don't think it can be measured reasonably with a kitchen scale. So I think for this recipe the conversion is OK. But feel free to add more information if you think it's not!

The control panel is definitely something I'm considering, it would be needed for some of the other enhancements...
