### ISSUE TITLE
Doesn't seem to work on bettycrocker.com

### ISSUE THREAD

**Issue by jjspear** [falk-hueffner/metric-cooking#20]
https://www.bettycrocker.com/recipes/peanut-butter-cookies/6aa18699-bad1-442a-97bf-388003acce2d

**Comment by diamondavocado** [comment]
I'm not the author but this will be because that site has separated the quantities and the unit of measures in the HTML source code itself. It would be very difficult for the extension to figure out what to convert without doing some extra processing such as stripping all the HTML tags before converting.

**Comment by falk-hueffner** [comment]
HTML looks like this:
```
<li class="ingredient">
                <span class="quantity">1/2</span>
                <span class="unitOfMeasure"></span>
                <span class="description">
cup granulated sugar                </span>
            </li>

```
so it's the same issue as #8 and #6.
