### ISSUE TITLE
1 pound = 450g, but 1½ pounds = 700g (?)

### ISSUE THREAD

**Issue by diamondavocado** [falk-hueffner/metric-cooking#21]
On this recipe:
https://persianmama.com/kabob-koobideh-grilled-minced-meat-kabobs/

The converted output reads:

> 1 ½ pounds [700 g] ground beef (80-85% lean)
> 1 pound [450 g] ground lamb (80-85% lean)

That is obviously wrong. If 1 lb is 450g then 1.5 lbs is 675g, not 700.

**Comment by falk-hueffner** [comment]
This comes from rounding. 1 pound is 453.592g and 1½ pounds is 680.389g. Since you don't want to read something like "453.592g", the extension rounds this to nicer reading numbers, accepting up to 3% error. This will unfortunately necessarily introduce the kinds of inconsistencies you're seeing, since we're sometimes rounding up and sometimes rounding down.

**Comment by falk-hueffner** [comment]
Closing since this can't be avoided with the current design.
